module.exports = Object.freeze({
    EMPRESA_CRIAR:"EMPRESA_CRIAR",
    EMPRESA_VISUALIZAR:"EMPRESA_VISUALIZAR",
    EMPRESA_EDITAR:"EMPRESA_EDITAR",
    
    CRIAR_SUPER_ADMIN:'CRIAR_SUPER_ADMIN',

    USUARIO_CRIAR:"USUARIO_CRIAR",
    USUARIO_VISUALIZAR:"USUARIO_VISUALIZAR",
    USUARIO_APAGAR:"USUARIO_APAGAR",
    USUARIO_ATUALIZAR:"USUARIO_ATUALIZAR",
    USUARIO_BUSCAR:"USUARIO_BUSCAR",

    
    ENTREGA_CRIAR:"ENTREGA_CRIAR",
    ENTREGA_VISUALIZAR:"ENTREGA_VISUALIZAR",
    ENTREGA_ALTERAR_STATUS:"ENTREGA_ALTERAR_STATUS",
    

    PEDIDO_CRIAR:'PEDIDO_CRIAR',
    PEDIDO_EDITAR:'PEDIDO_EDITAR',
    PEDIDO_VISUALIZAR:'PEDIDO_VISUALIZAR',
    PEDIDO_CANCELAR:'PEDIDO_CANCELAR',
    PEDIDO_ALTERAR_STATUS: "PEDIDO_ALTERAR_STATUS",

    CLIENTE_CRIAR:'CLIENTE_CRIAR',

    ENTREGADOR_CRIAR:'ENTREGADOR_CRIAR',

    FINANCEIRO_VISUALIZAR:'FINANCEIRO_VISUALIZAR',
    FINANCEIRO_EDITAR:'FINANCEIRO_EDITAR',

    PLATAFORMA_FINANCEIRO_VISUALIZAR:'PLATAFORMA_FINANCEIRO_VISUALIZAR',
    PLATAFORMA_FINANCEIRO_EDITAR:'PLATAFORMA_FINANCEIRO_EDITAR',

    PLATAFORMA_METRICAS_VISUALIZAR:'PLATAFORMA_METRICAS_VISUALIZAR',
    PLATAFORMA_CONFIGURAR:'PLATAFORMA_CONFIGURAR',

    PLANO_VISUALIZAR:'PLANO_VISUALIZAR',
    PLANO_EDITAR:'PLANO_EDITAR',
    COBRANCA_VISUALIZAR:'COBRANCA_VISUALIZAR',
    COBRANCA_EDITAR:'COBRANCA_EDITAR'
});
