module.exports = Object.freeze({
    EMPRESA_CRIAR:"EMPRESA_CRIAR",
    EMPRESA_VISUALIZAR:"EMPRESA_VISUALIZAR",
    EMPRESA_EDITAR:"EMPRESA_EDITAR",
    
    CRIAR_SUPER_ADMIN:'CRIAR_SUPER_ADMIN',

    USUARIO_CRIAR:"USUARIO_CRIAR",
    USUARIO_VISUALIZAR:"USUARIO_VISUALIZAR",
    USUARIO_APAGAR:"USUARIO_APAGAR",
    USUARIO_ATUALIZAR:"USUARIO_ATUALIZAR",
    USUARIO_BUSCAR:"USUARIO_BUSCAR",
    USUARIO_ALTERAR_SENHA:"USUARIO_ALTERAR_SENHA",

       
    
    PEDIDO_CRIAR:'PEDIDO_CRIAR',
    PEDIDO_EDITAR:'PEDIDO_EDITAR',
    PEDIDO_VISUALIZAR:'PEDIDO_VISUALIZAR',
    PEDIDO_ALTERAR_STATUS:"PEDIDO_ALTERAR_STATUS",
    PEDIDO_CANCELAR:'PEDIDO_CANCELAR',
    

    CLIENTE_CRIAR:'CLIENTE_CRIAR',

    ENTREGADOR_CRIAR:'ENTREGADOR_CRIAR',
    ENTREGADOR_ALTERAR_DADOS:'ENTREGADOR_ALTERAR_DADOS',
    ENTREGADOR_ADICIONAR_FOTO:'ENTREGADOR_ADICIONAR_FOTO',
    ENTREGADOR_CADASTRAR_VEICULO:'ENTREGADOR_CADASTRAR_VEICULO',
    ENTREGADOR_ALTERAR_VEICULO:'ENTREGADOR_ALTERAR_VEICULO',
    ENTREGADOR_ALTERAR_STATUS:'ENTREGADOR_ALTERAR_STATUS',
    ENTREGADOR_ALTERAR_SENHA:'ENTREGADOR_ALTERAR_SENHA',
    ENTREGADOR_VISUALIZAR:'ENTREGADOR_VISUALIZAR',

    FINANCEIRO_VISUALIZAR:'FINANCEIRO_VISUALIZAR',
    FINANCEIRO_EDITAR:'FINANCEIRO_EDITAR',

    PLATAFORMA_FINANCEIRO_VISUALIZAR:'PLATAFORMA_FINANCEIRO_VISUALIZAR',
    PLATAFORMA_FINANCEIRO_EDITAR:'PLATAFORMA_FINANCEIRO_EDITAR',

    PLATAFORMA_METRICAS_VISUALIZAR:'PLATAFORMA_METRICAS_VISUALIZAR',
    PLATAFORMA_CONFIGURAR:'PLATAFORMA_CONFIGURAR',

    PLANO_VISUALIZAR:'PLANO_VISUALIZAR',
    PLANO_EDITAR:'PLANO_EDITAR',
    COBRANCA_VISUALIZAR:'COBRANCA_VISUALIZAR',
    COBRANCA_EDITAR:'COBRANCA_EDITAR'
});
